### ISSUE TITLE
add support for open-vm-tools for specific OSfamilies

### ISSUE THREAD

**Issue by Phil-Friderici** [emahags/puppet-module-vmware#2]

**Comment by Phil-Friderici** [comment]
Suggestion:
vmware (init.pp):
switch between OSP and open-vm-tools depending on OSfamily (automagic) or hiera override (manual).

vmware::open-vm-tools
will handle the package installation via local repos

vmware::osp
will be a copy of existing code

@emahags what do you think ?

**Comment by emahags** [comment]
I had already updated the module before I saw this, sorry.

**Comment by Phil-Friderici** [comment]
after the update is before the update ;)

**Comment by Phil-Friderici** [comment]
never mind ;)
