### ISSUE TITLE
repo_package_name default

### ISSUE THREAD

**Issue by eabecho** [emahags/puppet-module-vmware#3]
The default is currently set to "vmwaretools-repo".  I would suggest making the default "vmware-tools-repo" to be consistent with the packages from VMware: 

http://packages.vmware.com/tools/esx/5.5latest/repos/index.html

    [DIR] Parent Directory                  05-Feb-2015 08:47     1k  
    [FILE] vmware-tools-repo-RHEL5-9.4.11..> 02-Feb-2015 10:26     2k 
    [FILE] vmware-tools-repo-RHEL5-9.4.11..> 02-Feb-2015 10:26     2k  
    [FILE] vmware-tools-repo-RHEL6-9.4.11..> 02-Feb-2015 10:26     2k  
    [FILE] vmware-tools-repo-RHEL6-9.4.11..> 02-Feb-2015 10:26     2k  
    [FILE] vmware-tools-repo-SLES11.0-9.4..> 02-Feb-2015 10:26     2k  
    [FILE] vmware-tools-repo-SLES11.0-9.4..> 02-Feb-2015 10:26     2k  
    [FILE] vmware-tools-repo-SLES11.1-9.4..> 02-Feb-2015 10:26     2k  
    [FILE] vmware-tools-repo-SLES11.1-9.4..> 02-Feb-2015 10:26     2k  
    [FILE] vmware-tools-repo-SLES11.2-9.4..> 02-Feb-2015 10:26     2k  
    [FILE] vmware-tools-repo-SLES11.2-9.4..> 02-Feb-2015 10:26     2k  
    [FILE] vmware-tools-repo-SLES11.3-9.4..> 02-Feb-2015 10:26     2k  
    [FILE] vmware-tools-repo-SLES11.3-9.4..> 02-Feb-2015 10:26     2k  
    [FILE] vmware-tools-repo-ubuntu10.04_..> 02-Feb-2015 10:26     1k  
    [FILE] vmware-tools-repo-ubuntu10.04_..> 02-Feb-2015 10:26     1k  
    [FILE] vmware-tools-repo-ubuntu11.04_..> 02-Feb-2015 10:26     1k  
    [FILE] vmware-tools-repo-ubuntu11.04_..> 02-Feb-2015 10:26     1k  
    [FILE] vmware-tools-repo-ubuntu11.10_..> 02-Feb-2015 10:26     1k  
    [FILE] vmware-tools-repo-ubuntu11.10_..> 02-Feb-2015 10:26     1k  
    [FILE] vmware-tools-repo-ubuntu12.04_..> 02-Feb-2015 10:26     1k  
    [FILE] vmware-tools-repo-ubuntu12.04_..> 02-Feb-2015 10:26     1k

**Comment by emahags** [comment]
This is no longer relevant as we don't use a package for the repo anymore, closing.
