### ISSUE TITLE
augeas dependency

### ISSUE THREAD

**Issue by philippvh** [emahags/puppet-module-vmware#9]
Hi Mathias,

when testing (e.g. stopping puppet, removing all VMware packages, re-enabling puppet) I've come across this:
```
Error: /Stage[main]/Vmware/Augeas[vmtools_conf_augeas]: Could not evaluate: Save failed with return code false, see debug
Notice: /Stage[main]/Vmware/Package[vmware-tools-esx-nox]/ensure: created
Notice: /Stage[main]/Vmware/Service[vmware-tools-services]: Dependency Augeas[vmtools_conf_augeas] has failures: true
Warning: /Stage[main]/Vmware/Service[vmware-tools-services]: Skipping because of failed dependencies
```
On next puppet run, it's working as intended.

I think this additional dependency within the augeas should prevent the issue (1 out of 1 test it worked):
```
      notify  => Service[$service_name_real],
      require => File['vmtools_conf'],
    }
```
Sorry I don't have a PR for this yet, but I won't make this today. I can, if you'd prefer.

BR/Philipp

**Comment by emahags** [comment]
Should be fixed now, thanks for the report!
